### ISSUE TITLE
Connection to Lightstreamer

### ISSUE THREAD

**Issue by AlessandroAlinone** [RailsStudyGroup/stationstream#3]
To get real-time data from the Lightstreamer Server, you should use the lightstreamer.js client library. It can run both in the browser and in the node server:
1) Browser-based simplest example: http://demos.lightstreamer.com/ISSLive/issmin.html 
2) Node version of the lib: https://www.npmjs.com/package/lightstreamer-client (same exact API of the browser-based version).

**Comment by mcmahoniel** [comment]
Thank you for the info! We're in the process of integrating that client into our project and look forward to seeing where it takes us.

**Comment by AlessandroAlinone** [comment]
Let us know if you need any help with the Lightstreamer API. You can also write directly to support@lightstreamer.com
