### ISSUE TITLE
Database entries should expire after a set time

### ISSUE THREAD

**Issue by RaceFPV** [RailsStudyGroup/stationstream#6]
example: http://stackoverflow.com/questions/25305385/meteor-collections-that-expire 

Subscription based database entries from lightstreamer to mongodb should be set to expire after a set period of time, to prevent database overflow.

Expire times should be set based on the expected amount of data for each particulary lightstreamer subscription. (ex. 1 day for telemetry, 7 days for radio on/off)

**Comment by mcmahoniel** [comment]
Fixed in 9cd310ac68606c6cc2e6b0d5f9a7c3816510afb1 by @4xposed
