### ISSUE TITLE
Create a clean JSON output of very latest data

### ISSUE THREAD

**Issue by RaceFPV** [RailsStudyGroup/stationstream#8]
Create a clean JSON output, with only one entry per data type collected from lightstreamer, to be used as an API page to allow others easy access to the collected information.

ex:

{ {telemetry: 
    {x: 333333},
    {y: 34444},
    {z: 4444}}
  {solar_panels:
    {rotatex: 124},
    {rotatey: 122}}
}

**Comment by 4xposed** [comment]
Wanted to assign us both, seems I can't do that, sorry for the mess

**Comment by 4xposed** [comment]
Partially solved in 370f817c0f879093557c98091c3bdc7207ebad25 by @4xposed

Now the endpoint `/api/isslocation/latest`returns such an object:

```
{
"status": "success",
  "data": {
    "positionx": "4151.31750926521",
    "positiony": "5062.83508358239",
    "positionz": "-1777.81517681853"
  }
}
```

**Comment by 4xposed** [comment]
Added solar data API endpoint in fc32d66e547c30cc0c3a7fd88c0a8e0f4de5c76f by @4xposed

I will merge it in master upon team approval 

The endpoint `/isssolar/latest` returns such an object:

```
{
  "status": "success",
  "data": {
    "SARJStarRotate": "198.300567626953",
    "SARJPortRotate": "198.300567626953",
    "Data_1A": {
      "voltage": "151.24511645",
      "rotate": "10.1953125"
    },
    "Data_1B": {
      "voltage": "151.24511645",
      "rotate": "325.266723632813"
    },
    "Data_2A": {
      "voltage": "151.142577388",
      "rotate": "145.184326171875"
    },
    "Data_2B": {
      "voltage": "151.142577388",
      "rotate": "200.275268554688"
    },
    "Data_3A": {
      "voltage": "151.24511645",
      "rotate": "349.766235351563"
    },
    "Data_3B": {
      "voltage": "151.347655512",
      "rotate": "34.7662353515625"
    },
    "Data_4A": {
      "voltage": "151.142577388",
      "rotate": "203.291015625"
    },
    "Data_4B": {
      "voltage": "151.347655512",
      "rotate": "188.96484375"
    }
  }
}
```

**Comment by 4xposed** [comment]
Added water and air data API endpoint in e95d69fa846e3a1aa2607b22989bd1bef9240abe by @4xposed

The endpoint  `/api/issairwater/latest` returns an object like this one:

```
{
  "status": "success",
  "data": {
    "air": {
      "o2": "166.405601269674",
      "n2": "582.366037637558",
      "co2": "3.59521143214196"
    },
    "h2o": {
      "bad": "60.09",
      "good": "89.72"
    },
    "cabin": {
      "pressure": "755.32064796875",
      "temp": "22.1288740720482"
    }
  }
}
```

**Comment by 4xposed** [comment]
Added computer data API endpoint in 6b096b1104d72811dd9fa1794e3971cbda95b11e by @4xposed

The endpoint  `/api/isscomputer/latest` returns an object like this one:

```
{
  "status": "success",
  "data": {
    "commandcount": "62006",
    "datacount": "13808",
    "pccount": "7"
  }
}
```
